hash-format = "sha256"

[[files]]
file = "config/BlossomMods/BlossomBack.json"
hash = "e32c07f4920eb46276359955ade4f1444c59a3990cad6faae9810faceb8f8c7a"

[[files]]
file = "config/BlossomMods/BlossomHomes.json"
hash = "3bb5924e9401ac3a1f5f51cf211b09dfac1f39ec0d161cff165479436a6bb6b9"

[[files]]
file = "config/BlossomMods/BlossomLib.json"
hash = "52187ed3376cee1908b067d1bc3d852c9e933d153f74150192ece95ec3717475"

[[files]]
file = "config/BlossomMods/BlossomTpa.json"
hash = "7b31225630ace1c5165ed13b19620085ce9fc7d77a274b83cfadb65535228fd2"

[[files]]
file = "config/BlossomMods/BlossomWarps.json"
hash = "78535b30a2a6f6e04a44c622a0188f738225c2b513855b659ce604099256bbc9"

[[files]]
file = "config/cobblemon/main.json"
hash = "56f514de0b790d0c5d9799f42b259f64367a2ef6e5d4959011d7a1fd6db00eff"

[[files]]
file = "config/cobblemon/spawning/best-spawner-config.json"
hash = "c1fda16ab41773c829af58da8513fd786c7147f50f2bfbea7a716e29b3fa9198"

[[files]]
file = "config/cobblemon_smartphone.json"
hash = "ec67c9183cf6437171c68cf19f1d61a09f93546c04178e2e4d0beacff152c9ff"

[[files]]
file = "config/cobblenav/server-config.json"
hash = "3148eb7b5531b36f0b144950be6c80f1bee388f755cab58ca33bd70ae1fe2cd5"

[[files]]
file = "config/mega_showdown/config.json"
hash = "6dc0b5e8c0adeba56f57b8dc217e20fcba1689f63c6871504e5d2d76cf8bdbc5"

[[files]]
file = "config/starterkit/descriptions/poke_default.txt"
hash = "f36149165a391d2f549008afa57a4e43de3d6bc211c200aad7dc14f2e4cc3ec0"

[[files]]
file = "config/starterkit/kits/poke_default.txt"
hash = "bd12ef0f9ba869cd566807d7a5916f11490dc03df4eaa3005f2c6372d08048d5"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "3e0ee20dd4023742a6eb44a0ca48512e6d28814825172bc893081543b11b928d"

[[files]]
file = "config/yosbr/options.txt"
hash = "ece0c8b4f66fc0d4ecda410076df1f8689f9ab37a673136e7bd41529395e79c9"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bd0848389894ffe9850efb36210060ff0ac3cc31c74af7f80a897de05df4caa2"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "60cd797dfe0cc7a6be4762120a05eed6e7068111b267e4da5993ef2229ce74dc"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "93f989575eec26f333d4253f1af961983ba4d5179e1c3237b643836b40614a43"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "ddbb4bf26d15027847e52f5b30479470299b9a8c687697309f0535d658b9944b"
metafile = true

[[files]]
file = "mods/blossomback.pw.toml"
hash = "1b830a55ddc540fe32e4bd5af1c7047c37183424192bde15c924af5cbbc1d460"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "7b50dcd1d36768c501827fb34934cdc730fbefe5e013f04d4dd39596c0761726"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "a78b9ce8ba37cbc249146e7a383f475bec11b2fd5c01786cc96280723dad1c87"
metafile = true

[[files]]
file = "mods/blossomtpa.pw.toml"
hash = "922029dfc00fa5255c633b44951670135e8ca2511e2c4d23f5860d9aa01cf193"
metafile = true

[[files]]
file = "mods/blossomwarps.pw.toml"
hash = "15c50f49baf1be51bf636ef47ad1d5e8c4cdb0782d525a910f5a8bce2f658781"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "941c3f358ef74f4fc99727e550106b8905d77cb4971321fd8ca4406e33b704a6"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7fe287ca1bed0ad67f37e62a5816da7b7ae59486102c5e4b7532f0a999444527"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "c48b5f8a4bd794dfe1ac97a4245616aa63376743980b8cfc4b82f646ba1d56d8"
metafile = true

[[files]]
file = "mods/cobblemon-counter.pw.toml"
hash = "5d512fabc2c8a37f06f1dfac21e99157aee56023e0af329095792b7eea676308"
metafile = true

[[files]]
file = "mods/cobblemon-let-me-spawn.pw.toml"
hash = "f574a256e12f27c64d06df38101cf28f8f348411f0b52547496e4ab80e91c7de"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "affdebfc7768f349bd283abd5a5ba5e031e9aac0a2866b6c0584cd953cb1c325"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "eb51c053d004eafca2bca4cb91f9fedcee372fdf78c89fbbc6914c0fd103fc99"
metafile = true

[[files]]
file = "mods/cobblemon-size-variations.pw.toml"
hash = "faa511b494c47bd9ade4ac0132a5123c0779991d70e47b17e2eacaa4f79b6c19"
metafile = true

[[files]]
file = "mods/cobblemon-smartphone.pw.toml"
hash = "fa11027f3f1ffe00a9e55a1f4087d3faa6cead371e098c6b060e2be06cfeddff"
metafile = true

[[files]]
file = "mods/cobblemon-spawn-alerts.pw.toml"
hash = "7e210b095832cd46a2b1abaf0c5d5fec4864dd3141ef474ef7aed7780331fd70"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
hash = "3e714a17d24cde3abc0f6a71e55bd1f111bc11a6394fbe2432e0455a6b567315"
metafile = true

[[files]]
file = "mods/cobblemon-unchained.pw.toml"
hash = "625dece6fd04e674e0a8cba7d95d4cae21b8e291122016f8a6814ae66a35b732"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "d0d21c8cd26fc4ddcdd03893e4b7ad5e1d1a4701a272f002f2932f9686770a6e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "faaff57c5b26e464bebc517f3ead8df1ccc5050affa8340f309579ea0088fc15"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "d5cf6e8f1f0963a1b0bbaf54f3afe9a429706572f47a86c30fa4f23b72d04594"
metafile = true

[[files]]
file = "mods/easy-elytra-takeoff.pw.toml"
hash = "96973d668da9b7307f61885e605bf7d3042abae740b639258d72a34287e46fce"
metafile = true

[[files]]
file = "mods/enchanting-infuser-add-treasure-enchantments.pw.toml"
hash = "5e6f54349621f6be7ff92852910ccffe7378031c4b60e780a3a8dcf1f15bf2f7"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "466a02bb8e4145a4ae20926dc400838769acb2961e58aa3df57aa061b8b0a333"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4898b9beb1b7cf7df38346b02d9756c10e09408b6344e3295fe7177b25549f14"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "52eff5c4364676432feed4f4ea8b8a9441d4d95b84d4c434891063c99c05029c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1824d1cc8f4f82a88972b9220dc6806c05968d651fb38f6bfe69e4d8215fc0ed"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "9642962bbcc8bfd0fc299df9858ba7e9ff8d25a6d69a6df976577d9cb219f442"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
hash = "5f67c621095cc9e107d2a379b3fca4bd844f51f9a8e11a560daf107bb0320f03"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "a104f2f6044d43bbc5a5badc6f589b2f6f5a1b9c9e47e00dfbad5061aa3b51f4"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "e5a2b00a5a99de7ed4cf8184a60307afeecc4dce5ae0fb073cef29bef42e9826"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "502d4ba2ca8c7f6f52830cfc43fc12b567023266f2b557ee2b8eea737b58f8ea"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "c12090d1aa1239085a4b3d790900823ad14a40eacbd8fa42d9626d22995a8a80"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f5f134844b199b78f07b6f58ded80ee7b6a786d509a95687a2abb48e8dffee6b"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "2a351e405d3bbf633a34f4a08deb1f4aacbcff960f4e6e44fbb67fe0e07e3044"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "ec897286bdccb5d9fbef02b1c9070a9bce343f592cfc22aea3c836f0446e1864"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "8675eb41c4bb4fb257451f86a79ae35aae0ce5d88a061e1adcaede311c22f4aa"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1197c76400a13a3961f70538d7acf7764436fc92899cca5bd05b9bf3027601c2"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "8d4ecc66f120419b4bc09fdd14151d2a207ddec30b46ae2184300fec0031b092"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "e452f90984a20b6848e2a22493d462c597e1d0b9f10b15f6098fc56e390de376"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "70ec6df06813b68cf3082c5a52339d32397c200f6acc8c02170453200bd79165"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "6803e0debba4fb27c735ccb139d26ae4c7744b8a7d2ac500d4f56b1d411faeea"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "f53b91397b8a969e843af8772db448ab1c9bc556233a3b26266c52cfa77950fe"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "acc5199aefdbb418065cf4f3554693fcf9797dc1851a36ca7bad9e660b127763"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "d22546ad55b555931eb527f163b3564e00c12c7dc8101378b87447dfcc8e0652"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/roughly-enough-professions-rep.pw.toml"
hash = "bd3ed617e2811d333650b81b3fe2b800bac12628f262ce4867b86ad41c4e3748"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "ceb180c764fa9c7c12c7e750cc7b726171277cb2b68e47370888c4ff4679a4ed"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "90d1f4ee70f4b208b623af04b48be8fd5b98b411cbd4d9d0a5b23d07ba99c1e4"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "27f2a11921312246d216d0c0c021f9c2602e5a06fb17ba6f8c12ee8542d8826a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "a4eebb2bda9daccc5444b8bd2d91f4ee8ce2325dd51436cb785ca33530b98ecd"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "693fdc79c18086a2a939b45de97ca918d895d5a4247d2a0bba94bf53661bc705"
metafile = true

[[files]]
file = "mods/squaremap.pw.toml"
hash = "006ab468593800134c0bbf0ffdf8e90586c55da712cfc0e2dbe2f6c44757e15b"
metafile = true

[[files]]
file = "mods/starter-kit.pw.toml"
hash = "ea33d99764a8bae0618db5fc2eebec624f72f49bd6189b9818eb214687f71a82"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e35593590fe988653baebae4638f6c93b5d822351274955cc1288b34fe5429fe"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "11dc9ff856643ec1c9833fb821760c86e6a0ae7fca8c31769a385549237c96c9"
metafile = true

[[files]]
file = "mods/veinminer-client.pw.toml"
hash = "63d11abf43619941f5dfa77daccf9eac417cd20f82868bed1014d5bf6e7e1681"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "79a914c22a29620290a146689b8f37fa3c707c590a1edcca9665eff659b1562e"
metafile = true

[[files]]
file = "mods/watson.pw.toml"
hash = "ca208d3bc705a00cee422c54ff4e06388be6dde10bf2175137512a250985657d"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "896dc18c8839f179aca6e9a7891de85898a4f5814a35249781d3efda33d29091"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8f391603f2b1aaf63717c180e82635b7cd2d57617c02edac60f9d25244731df1"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "58eb7f330c8e2158385fda1a391b1a93faf36459f8d25ccb482e26ce885deb5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2d0ca6e5a2077ae624a65a5310f36ddd6736de699748ac3959022e03844e2f52"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "4d98bdba90cdeae788a747bb6fe7d438ba49fdc4eb67c38d4573304eec4a2ef8"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "57c6e291ce10527ca8672b0ab508dea77afa067b7ec5daf772904cf2105e5e1e"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "30c81f667b06ad090542f51753645ca8541908c225cc0d9106f725560eb51914"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "ffcf32caf3dda8f05adb109dc86c477cf1bb768bac6232bc5bcf0d60a7861bcb"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "a9f7ce3ef90cd500e451ff6534d42f0532150d5f207c974468295fbe8c7b5a47"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "9ebe3f899af40f9bec87d76c2c3dc85004278d30165fcbc0020a11d47da5d35e"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "eccab4f9bcbc604767e9794ca746588f673db63f85bd63adf0b505b396a3c23c"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "a33c822c6525c8b708475161e263cb18883332383a6b25e2b5915623f0e5b85c"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "15ef858f138af87eb7376988107cb6f61bccf578c4c8bcca44a473a0ca128e41"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "66e4fca8e34915da64ec530a9153500271016e2086752a7f196f71a5c6135d84"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "1bd0ba1128e6ae3f926298c2ffe33180cca75362fae3bd92146d43977297f01c"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "f0779c5ec85b19542d39dd3df11c0fd521c465f5da2bafc9d1a6250a30719cc6"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "57ae99f727e3fcd7a1abbc624bf14cafa5f092f2082dcf3edc609289efb25c15"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "b7152fd543e5efd1233dfc49ddb690332d98bdb986b4b7a289565fbf3af6cbe5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true

[[files]]
file = "squaremap/config.yml"
hash = "cbb86e3a1320d5dd7bebe5709cddea7e6b477dbfbe6f4cc8348b27ffcd0b9813"
