name = "Mc Dev Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5d71b41dd0430255fb41a64109c115c34c4c01eb4a570d17f5469a23de2b90c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
