name = "Mc Dev Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "384117881db1b7268e6d53a1f62383c78ed47886a639e739b636c763a5ac83a2"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
