name = "Mc Dev Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb324be026d4db65e6807db1ae0c1bc37b4c3ef737edc070174b0341bdc21d32"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
