name = "village pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "813ed7a26967978884cf68b44e9b0e9c1ff842d63ef9d544e3f6abb0ff3e47b5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
