name = "Mc Dev Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd7f32c89b062d45dc254466a00580fc3d189c823bec54f8d52f8bdcdec8296"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
