name = "village pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d4d98eb3711a27c2af16fc53c89a154612647e72a4dfd4e04fce071530f627"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
