name = "village pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb98be5e3149ba2f56f0ab0ff9217b5261af4b5543ce3c748a939e604a4d0d1e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
